name: Runtest

on:
  schedule:
   - cron: '0 16 * * *'
  push:
   branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.x.x # use the explicit version number
        with:
          build: npm run build
          start: npm start

      - name: Download chrome
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable

      - name: Running tests
        run: |
          behave node_modules/gmail-tester-extended/init.js credentials-test-automation-1.json token-test-automation-1.json test-automation-1@getluna.com
